apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-8cyy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-8cyy
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-8cyy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-8cyy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-8cyy
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kwuy-tenant/rhtap-demo-app/hacbs-test-project-8cyy@sha256:50dd04c59088f302d0ce45ab2c835d32b5fa02f6fcc3a5befb3b9aedd5c7dc08
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
